name: 'edtech_analytics'
version: '1.0'
config-version: 2

profile: 'edtech_clickhouse'

model-paths: ["models"]

models:
  edtech_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
