models:
  - name: user_activity_daily
    description: "DAU и активность пользователей"
    columns:
      - name: event_date
        tests: [not_null]
      - name: sessions_count
        tests: [not_null]

  - name: task_performance_daily
    description: "Успешность решений задач"
    columns:
      - name: tasks_successful
        tests: [not_null]

  - name: user_payments
    description: "История покупок пользователей"
    columns:
      - name: user_id
        tests: [not_null]

  - name: events_flat
    description: "Сырые события, нормализованные из JSON"
    columns:
      - name: event_time
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: event_type
        tests: [not_null]

  - name: user_retention
    description: "Когорты пользователей и их ретеншн"
    columns:
      - name: cohort_date
        tests: [not_null]
      - name: day_offset
        tests: [not_null]
      - name: retained_users
        tests: [not_null]

  - name: ab_test_metrics
    description: "Метрики A/B тестов по активным пользователям"
    columns:
      - name: test_id
        tests: [not_null]
      - name: variant
        tests: [not_null]
      - name: metric_name
        tests: [not_null]
      - name: value
        tests: [not_null]
